# Generated by Django 5.0.6 on 2024-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_order_is_deliver_order_is_ordered_order_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('customer', models.CharField(max_length=255)),
            ],
        ),
    ]
