# Generated by Django 5.0.6 on 2024-06-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
