# Generated by Django 5.0.6 on 2024-06-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_payment_receipt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
    ]
