# Generated by Django 5.0.6 on 2024-06-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_rename_order_payment_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
