# Generated by Django 5.0.6 on 2024-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0011_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
