# Generated by Django 5.0.6 on 2024-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0013_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
